services:
  case-creditas-api:
    container_name: case-creditas-api
    image: case-creditas-api
    mem_limit: 4096m
    cpus: 4.0
    networks:
      proxy:
        ipv4_address: ${DOCKER_CREDITAS_API_CONTAINER_IP}
    ports:
      - "${DOCKER_CREDITAS_API_CONTAINER_EXTERNAL_PORT}:${DOCKER_CONTAINER_CREDITAS_API_INTERNAL_PORT}"
    environment:
      - APP_PORT=${CREDITAS_SPRING_PORT}
      - SERVER_TOMCAT_THREADS_MAX=${CREDITAS_API_SERVER_TOMCAT_THREADS_MAX}
      - MAIL_HOST=${CREDITAS_API_MAIL_HOST}
      - MAIL_PORT=${CREDITAS_API_MAIL_PORT}
      - MAIL_USERNAME=${CREDITAS_API_MAIL_USERNAME}
      - MAIL_PASSWORD=${CREDITAS_API_MAIL_PASSWORD}
      - MAIL_ENABLED=${CREDITAS_API_MAIL_ENABLED}
networks:
  proxy:
    external: true
