services:
  case-creditas-api:
    container_name: case-creditas-api
    image: case-creditas-api
    mem_limit: 4096m
    cpus: 4.0
    networks:
      proxy:
        ipv4_address: ${DOCKER_CREDITAS_API_CONTAINER_IP}
    ports:
      - "${DOCKER_CREDITAS_API_CONTAINER_EXTERNAL_PORT}:${DOCKER_CONTAINER_CREDITAS_API_INTERNAL_PORT}"
    environment:
      - APP_PORT=${CREDITAS_SPRING_PORT}
      - SERVER_TOMCAT_THREADS_MAX=${CREDITAS_API_SERVER_TOMCAT_THREADS_MAX}
      - SPRING_PROFILES_ACTIVE=${CREDITAS_API_ACTIVE_PROFILE}
networks:
  proxy:
    external: true
