spring:
  application:
    name: creditas
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:devdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true
server:
  tomcat:
    threads:
      max: 250
    accept-count: 100
