spring:
  mail:
    enabled: ${MAIL_ENABLED:false}
    host: ${MAIL_HOST:host-fallback}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:username-fallback}
    password: ${MAIL_PASSWORD:password-fallback}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: creditas
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:devdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  threads:
    virtual:
      enabled: true
server:
  tomcat:
    threads:
      max: ${SERVER_TOMCAT_THREADS_MAX:200}
